name: Lektor Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8.6
      - run: |
          pip install --upgrade pip
          if [ -e requirements.txt ]; then pip install -r requirements.txt; fi
          lektor build --output-path ./site
          echo "secrets\n##########"
          echo ${{ secrets }}
          echo "\n###############"
          echo ${{ secrets.ACCESS_TOKEN }}
          echo "\n################"
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: luizfnunes@outlook.com
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: site
          CNAME: luizfnunes.zonafantasma.net
      
