# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: GitHub Pages Pelican Build Action
      # You may pin to the exact commit or the version.
      # uses: nelsonjchen/gh-pages-pelican-action@1c5878bc50b894b2bede964dace03313f3dbd4be
      uses: nelsonjchen/gh-pages-pelican-action@0.1.6
      with:
        # override the default `gh-pages` deployment branch
        GH_PAGES_BRANCH: web
