name: Pelican Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Lektor Action
      # You may pin to the exact commit or the version.
      # uses: VaultVulp/lektor-action@977fc5d066d1d31f259260278fc420c8e86b9d60
      uses: VaultVulp/lektor-action@v1.0.2
